  const translations = {
  kz: {
    toStart: "Басты",
    accountCourse: "Бухгалтерия б/а курсылар",
    soprovag: "Бухгалтерлік сүйемелдеу",
    consulta: "Кеңес беру",
    course1C: "1С бойынша курстар",
    compGramCourse: "Компьютерлік сауаттылық курсы",
    contact: "Байланыс",
    bgVer: "Бухгалтерия#1C#Сүйемелдеу#Курсылар",
    aboutMainText: "Алматыдағы бухгалтерлік қызмет",
    videoName: '«Негізінен теңгерімге дейін» курсына кіріспе сабағы',
    accCourseTitle: "Бухгалтерия б/а курсылар",
    accCourseFotmat: "Курстар онлайн және оффлайн пішімінде жүргізіледі.",
    firstAccCourseTitle: "Үздіксіз мысалды қолдану арқылы 1С тілінде «Негізінен теңгерімге дейін» курсы - 39 000 теңге",
    firstAccCourseContains: "Бұл курс барысында сіз келесі есептерді жасауды үйренесіз:",
    firstAccCourseContainsFT: "— Баланс",
    firstAccCourseContainsST: "— Ақша қаражаттарының қозғалысы туралы есеп",
    firstAccCourseContainsTT: "— Пайда мен залал туралы есеп",
    "secondAccCourseTitle": "«Салық салу» курсы 1С-те нақты мысал арқылы — 39 000 тг",
  "secondAccCourseContains": "Курс аясында сіз келесі нысандарды толтыруды үйренесіз:",
  "secondAccCourseContainsFT": "— 100 нысан (ККС – корпоративтік кіріс салығы)",
  "secondAccCourseContainsST": "— 200 нысан (ЖТС – жалақы салығы)",
  "secondAccCourseContainsTT": "— 300 нысан (ҚҚС – қосылған құн салығы)",
  "soprovagIP": "— ЖК үшін 50 000 тг бастап",
  "soprovagTOO": "— ЖШС үшін 90 000 тг бастап",
  "consultaTime": "- Ұзақтығы 30 минут",
  "consultaPrice": "- Қызмет құны 10 000 тг",
  "consultaInfo": "Кеңес онлайн не офлайн түрде өткізіледі. Міндетті түрде алдын ала жазылып, толық төлем жасау қажет.",
  "course1CTitle": "1С бағдарламалау курсы",
  "course1CPrice": "Бағасы - 79 000 тг",
  "course1CPredTitle": "Курс - 1С Кәсіпорын",
  "course1CPredPrice": "Бағасы - 29 000 тг",
  "compGramCourse": "Курс - Компьютерлік сауаттылық",
  "compGramCoursePrice": "Бағасы - 12 000 тг",
  "address": "Мекенжайы:",
    addressLink: "Шевченко көшесі, 85",
  },
  ru: {
    toStart: "Главное",
    accountCourse: "Курсы по бухгалтерии",
    soprovag: "Бухгалтерское сопровождение",
    consulta: "Консультация",
    course1C: "Курсы по 1С",
    compGramCourse: "Курс по Компьютерной грамотности",
    contact: "Контакты",
    bgVer: "Бухгалтерия#1C#Сопроваждение#Курсы",
    aboutMainText: "Бухгалтерское обслуживание в Алмате",
    videoName: 'Вводный урок к курсу "от Азов до Баланса"',
    accCourseTitle: "Курсы по бухгалтерии",
    accCourseFotmat: "Курсы проводяться в онлайн и оффлайн формате.",
    firstAccCourseTitle:"Курс «От азов до баланса» в 1С на сквазном примере — 39 000 тг",
    firstAccCourseContains: "В рамках курса вы научитесь составлять следующие отчёты:",
    firstAccCourseContainsFT: "— Баланс",
    firstAccCourseContainsST: "— Отчёт о движении денежных средств",
    firstAccCourseContainsTT: "— Отчёт о прибылях и убытках",
    secondAccCourseTitle: "Курс «Налогообложение» в 1С на сквазном примере — 39 000 тг",
    secondAccCourseContains: "В рамках курса вы научитесь заполнять следующие формы:",
    secondAccCourseContainsFT: "— форму 100 (КПН - корпоративный подоходный налог)",
    secondAccCourseContainsST: "— форму 200 (ИПН - налоги по зарплате)",
    secondAccCourseContainsTT: "— форму 300 (НДС - налог на добавленную стоимость)",
    soprovagIP: "— от 50 000 тг для ИП",
    soprovagTOO: "— от 90 000 тг для ТОО",
    consultaTime: "- Продолжительность 30 минут",
    consultaPrice: "- Стоимость услуги 10 000 тг",
    consultaInfo: "Может проводиться как онлайн, так и в оффлайн формате. Обязательно нужно записаться с полной предоплатой.",
    course1CTitle: "Курс програмирование в 1С",
    course1CPrice: "Стоимость - 79 000 тг",
    course1CPredTitle: "Курс - 1С Предприятие",
    course1CPredPrice: "Стоимость - 29 000 тг",
    compGramCourse: "Курс - Компьютерная грамотность",
    compGramCoursePrice: "Стоимость - 12 000 тг",
    address: "Адрес:",
    addressLink: "Улица Шевченко, 85",
  }
};

function switchLanguage(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    el.textContent = translations[lang][key];
  });
  console.log("shit");
}

